% you should probably change the below two paths
addpath('./229/cs229-accent-classification/lib/rastamat/');
audio_dir = './229/audio/words2';

files = dir([audio_dir '/*.wav']);

d = [];
for f = 1:1 % 1:length(files) 
    [d_curr, sr] = audioread(fullfile(audio_dir, files(f).name));
    d = [d; d_curr(:,1)];
end

% mfcc 
[mm,aspc] = melfcc(d*3.3752, sr, ...
    'maxfreq', 8000, ...
    'numcep', 20, ...
    'nbands', 22, ...
    'fbtype', 'fcmel', ...
    'dcttype', 1, ...
    'usecmp', 1, ...
    'wintime', 0.032, ...
    'hoptime', 0.016, ...
    'preemph', 0, ...
    'dither', 1);